name: FarmZones
main: com.cgixe.farmzones.Farmzones
version: 1.2.1
author: cgixe

description: Create zones in your farms for auto replanting

api-version: 1.19

commands:
  farmzones:
    description: Display the help menu for FarmZones
    usage: /farmzones
  farmzones create:
    description: Create a new FarmZones farm
    usage: /farmzones create [name]
  farmzones add:
    description: Add zones to a FarmZones farm
    usage: /farmzones add [farm name] [zone name] [pos1|pos2] [wheat|carrot|potato|beetroot|netherwart]
  farmzones delete farm:
    description: Delete FarmZones farm and all its zones
    usage: /farmzones delete farm [farm name]
  farmzones delete zone:
    description: Delete FarmZones zone from a farm
    usage: /farmzones delete zone [farm name] [zone name]
  farmzones harvest:
    description: Harvest a FarmZones farm
    usage: /farmzones harvest [farm name]
  farmzones replant:
    description: Replant a FarmZones farm
    usage: /farmzones replant [farm name]
  farmzones list:
    description: Lists all owned FarmZones farms
    usage: /farmzones list
  farmzones detail:
    description: Lists details of a FarmZones farm
    usage: /farmzones detail [farm name]
  farmzones harvest-all:
    description: Harvests all owned FarmZones farms
    usage: /farmzones harvest-all
  farmzones replant-all:
    description: Replants all owned FarmZones farms
    usage: /farmzones replant-all
  farmzones harvest-replant:
    description: Harvests and then replants a FarmZones farm
    usage: /farmzones harvest-replant [farm name]
  farmzones harvest-replant-all:
    description: Harvests and then replants all owned FarmZones farms
    usage: /farmzones harvest-replant-all
  farmzones bonemeal:
    description: Applies bonemeal to all crops in a FarmZones farm
    usage: /farmzones bonemeal [farm name]
  farmzones bonemeal-all:
    description: Applies bonemeal to all crops in all FarmZones farms
    usage: /farmzoens bonemeal-all